"""
tests/test_api_config.py — Playwright-Omni api_config TDD
Generated by p3-mattpocock-harness Solo Mode
"""

import pytest
import sys
from pathlib import Path

# Add scripts to path for imports
SCRIPTS_DIR = Path(__file__).parent.parent / "scripts"
sys.path.insert(0, str(SCRIPTS_DIR))


class TestApiConfig:
    """TDD tests for api_config module"""

    def test_api_key_is_non_empty_string(self):
        """API Key 应该是非空字符串"""
        from api_config import OPENAI_API_KEY
        assert isinstance(OPENAI_API_KEY, str)
        assert len(OPENAI_API_KEY) > 0, "API Key should not be empty"

    def test_api_base_url_format(self):
        """Base URL 应该是有效格式"""
        from api_config import OPENAI_BASE_URL
        assert OPENAI_BASE_URL.startswith("https://")
        assert ".com" in OPENAI_BASE_URL or ".ai" in OPENAI_BASE_URL

    def test_device_mode_valid_values(self):
        """Device Mode 应该是有效值之一"""
        from api_config import DEVICE_MODE
        assert DEVICE_MODE in ["auto", "cpu", "cuda"], \
            f"DEVICE_MODE should be one of ['auto', 'cpu', 'cuda'], got {DEVICE_MODE}"

    def test_hf_cache_path_is_d_format(self):
        """HF Cache 路径应该在 D: 盘"""
        from api_config import HF_CACHE
        assert HF_CACHE.startswith("D:\\") or HF_CACHE.startswith("D:/"), \
            "HF_CACHE should be on D: drive to protect C: drive"
