"""
tests/test_orchestrator.py — Playwright-Omni orchestrator TDD
Generated by p3-mattpocock-harness Solo Mode
"""

import pytest
import sys
import os
import json
import tempfile
import shutil
from pathlib import Path
from unittest.mock import MagicMock, patch

# Add scripts to path for imports
SCRIPTS_DIR = Path(__file__).parent.parent / "scripts"
sys.path.insert(0, str(SCRIPTS_DIR))


class TestStepRecord:
    """TDD tests for StepRecord dataclass"""

    def test_step_record_creation(self):
        """StepRecord 应该能正确创建"""
        from orchestrator import StepRecord

        step = StepRecord(
            step=1,
            action="click",
            target="button[name='login']",
            value="",
            thought="点击登录按钮",
            omni_elements_count=5,
            omni_time_ms=150.5,
            decision_time_ms=200.3,
            success=True,
            error=""
        )

        assert step.step == 1
        assert step.action == "click"
        assert step.success is True
        assert step.error == ""

    def test_step_record_with_error(self):
        """StepRecord 应该有 error 字段默认值"""
        from orchestrator import StepRecord

        step = StepRecord(
            step=1,
            action="click",
            target="button[name='login']",
            value="",
            thought="点击登录按钮",
            omni_elements_count=5,
            omni_time_ms=150.5,
            decision_time_ms=200.3,
            success=False
        )

        assert step.success is False
        assert step.error == ""  # 默认空字符串


class TestAgentResult:
    """TDD tests for AgentResult dataclass"""

    def test_agent_result_default_values(self):
        """AgentResult 默认值测试"""
        from orchestrator import AgentResult

        result = AgentResult()

        assert result.status == "error"
        assert result.total_steps == 0
        assert result.total_time_seconds == 0.0
        assert result.steps == []
        assert result.final_url == ""
        assert result.error_message == ""

    def test_agent_result_to_dict(self):
        """to_dict() 应该返回正确的字典格式"""
        from orchestrator import AgentResult, StepRecord

        step = StepRecord(
            step=1,
            action="click",
            target="button",
            value="",
            thought="test",
            omni_elements_count=5,
            omni_time_ms=100.0,
            decision_time_ms=150.0,
            success=True
        )

        result = AgentResult(
            status="success",
            total_steps=1,
            total_time_seconds=5.5,
            steps=[step],
            final_url="https://example.com",
            error_message=""
        )

        d = result.to_dict()

        assert d["status"] == "success"
        assert d["total_steps"] == 1
        assert d["total_time_seconds"] == 5.5
        assert len(d["steps"]) == 1
        assert d["final_url"] == "https://example.com"
        assert d["error_message"] == ""

    def test_agent_result_to_dict_rounds_time(self):
        """to_dict() 应该四舍五入 total_time_seconds 到 2 位小数"""
        from orchestrator import AgentResult

        result = AgentResult(total_time_seconds=5.56789)
        d = result.to_dict()

        assert d["total_time_seconds"] == 5.57

    def test_agent_result_summary_success(self):
        """summary() 应该正确格式化成功状态"""
        from orchestrator import AgentResult

        result = AgentResult(
            status="success",
            total_steps=10,
            total_time_seconds=30.5
        )

        summary = result.summary()

        assert "[BrowserAgent] Status: success" in summary
        assert "Steps: 10" in summary
        assert "Time: 30.5s" in summary
        assert "Error" not in summary  # 成功时不应该有 Error 行

    def test_agent_result_summary_with_error(self):
        """summary() 应该在有错误时显示错误信息"""
        from orchestrator import AgentResult

        result = AgentResult(
            status="error",
            total_steps=5,
            total_time_seconds=10.0,
            error_message="Connection timeout"
        )

        summary = result.summary()

        assert "[BrowserAgent] Status: error" in summary
        assert "Error: Connection timeout" in summary


class TestScreenshotManager:
    """TDD tests for ScreenshotManager"""

    def test_screenshot_manager_creates_directory(self):
        """ScreenshotManager 应该创建输出目录"""
        from orchestrator import ScreenshotManager

        temp_dir = tempfile.mkdtemp()
        try:
            mgr = ScreenshotManager(output_dir=temp_dir)

            assert mgr.output_dir == temp_dir
            assert mgr.screenshots == []
            assert Path(temp_dir).exists()
        finally:
            shutil.rmtree(temp_dir, ignore_errors=True)

    def test_screenshot_manager_default_dir(self):
        """ScreenshotManager 默认目录应该是 browser_agent_screenshots"""
        from orchestrator import ScreenshotManager
        import os

        mgr = ScreenshotManager()
        assert "browser_agent_screenshots" in mgr.output_dir

    def test_screenshot_capture_returns_path(self):
        """capture() 应该返回截图文件路径"""
        from orchestrator import ScreenshotManager

        temp_dir = tempfile.mkdtemp()
        try:
            mgr = ScreenshotManager(output_dir=temp_dir)

            # Mock page object
            mock_page = MagicMock()
            mock_page.screenshot = MagicMock(return_value=None)

            path = mgr.capture(mock_page, step=1, label="test")

            assert path.endswith(".png")
            assert "step_001" in path
            assert "test" in path
            assert path in mgr.screenshots
            mock_page.screenshot.assert_called_once()
        finally:
            shutil.rmtree(temp_dir, ignore_errors=True)

    def test_screenshot_capture_without_label(self):
        """capture() 不带 label 时不应该有下划线"""
        from orchestrator import ScreenshotManager

        temp_dir = tempfile.mkdtemp()
        try:
            mgr = ScreenshotManager(output_dir=temp_dir)

            mock_page = MagicMock()
            mock_page.screenshot = MagicMock(return_value=None)

            path = mgr.capture(mock_page, step=5)

            assert "step_005" in path
            assert "_" not in path.split("step_005")[1]
        finally:
            shutil.rmtree(temp_dir, ignore_errors=True)

class TestBrowserAgentApiKey:
    """TDD tests for BrowserAgent._get_api_key()"""

    def test_get_api_key_from_instance_variable(self):
        """_get_api_key() 应该返回实例变量中的 api_key"""
        from orchestrator import BrowserAgent

        agent = BrowserAgent(api_key="sk_test_12345")
        key = agent._get_api_key()

        assert key == "sk_test_12345"

    def test_get_api_key_from_env_variable_openai(self):
        """_get_api_key() 应该从环境变量获取 OpenAI key"""
        import os
        from orchestrator import BrowserAgent

        os.environ["OPENAI_API_KEY"] = "sk_env_67890"
        try:
            agent = BrowserAgent()  # 不传 api_key
            key = agent._get_api_key()

            assert key == "sk_env_67890"
        finally:
            del os.environ["OPENAI_API_KEY"]

    def test_get_api_key_prefers_instance_over_env(self):
        """实例变量优先于环境变量"""
        import os
        from orchestrator import BrowserAgent

        os.environ["OPENAI_API_KEY"] = "sk_env_67890"
        try:
            agent = BrowserAgent(api_key="sk_instance_priority")
            key = agent._get_api_key()

            assert key == "sk_instance_priority"
        finally:
            del os.environ["OPENAI_API_KEY"]

    def test_get_api_key_returns_none_when_missing(self):
        """没有 api_key 且环境变量也不存在时返回 None"""
        import os
        from orchestrator import BrowserAgent

        # 确保环境变量不存在
        if "OPENAI_API_KEY" in os.environ:
            del os.environ["OPENAI_API_KEY"]

        agent = BrowserAgent()
        key = agent._get_api_key()

        assert key is None

    def test_get_api_key_env_mapping_zhipu(self):
        """zhipu provider 应该读 ZHIPU_API_KEY 环境变量"""
        import os
        from orchestrator import BrowserAgent

        os.environ["ZHIPU_API_KEY"] = "sk_zhipu_test"
        try:
            agent = BrowserAgent(llm_provider="zhipu")
            key = agent._get_api_key()

            assert key == "sk_zhipu_test"
        finally:
            del os.environ["ZHIPU_API_KEY"]

    def test_screenshot_cleanup(self):
        """cleanup() 应该删除所有截图"""
        from orchestrator import ScreenshotManager

        temp_dir = tempfile.mkdtemp()
        try:
            mgr = ScreenshotManager(output_dir=temp_dir)

            # 手动添加一些假的截图路径
            fake_path1 = os.path.join(temp_dir, "fake1.png")
            fake_path2 = os.path.join(temp_dir, "fake2.png")

            # 创建文件
            Path(fake_path1).touch()
            Path(fake_path2).touch()

            mgr.screenshots = [fake_path1, fake_path2]

            mgr.cleanup()

            assert len(mgr.screenshots) == 0
            assert not Path(fake_path1).exists()
            assert not Path(fake_path2).exists()
        finally:
            shutil.rmtree(temp_dir, ignore_errors=True)

    def test_get_api_key_env_mapping_doubao(self):
        """doubao provider 应该读 ARK_API_KEY 环境变量"""
        import os
        from orchestrator import BrowserAgent

        os.environ["ARK_API_KEY"] = "sk_doubao_test"
        try:
            agent = BrowserAgent(llm_provider="doubao")
            key = agent._get_api_key()

            assert key == "sk_doubao_test"
        finally:
            del os.environ["ARK_API_KEY"]
