"""
tests/test_device_selector.py — Playwright-Omni device_selector TDD
Generated by p3-mattpocock-harness Solo Mode
"""

import pytest
import sys
from pathlib import Path

# Add scripts to path for imports
SCRIPTS_DIR = Path(__file__).parent.parent / "scripts"
sys.path.insert(0, str(SCRIPTS_DIR))


class TestEstimateTaskComplexity:
    """TDD tests for estimate_task_complexity function"""

    def test_complex_keywords_returns_complex(self):
        """包含复杂关键词应该返回 'complex'"""
        from device_selector import estimate_task_complexity

        complex_goals = [
            ("https://github.com", "登录GitHub"),
            ("https://amazon.com", "完成支付下单"),
            ("https://form.com", "填写注册表单"),
        ]

        for url, goal in complex_goals:
            result = estimate_task_complexity(url, goal)
            assert result == "complex", f"Expected 'complex' for '{goal}', got '{result}'"

    def test_simple_keywords_returns_simple(self):
        """包含简单关键词应该返回 'simple'"""
        from device_selector import estimate_task_complexity

        simple_cases = [
            ("https://example.com", "打开页面"),
            ("https://news.com", "浏览新闻"),
            ("https://shop.com", "查看商品"),
            ("https://search.com", "搜索内容"),
        ]

        for url, goal in simple_cases:
            result = estimate_task_complexity(url, goal)
            assert result == "simple", f"Expected 'simple' for '{goal}', got '{result}'"

    def test_multi_tab_keywords_returns_multi_tab(self):
        """包含多标签关键词应该返回 'multi_tab'"""
        from device_selector import estimate_task_complexity

        result = estimate_task_complexity("https://example.com", "打开新标签")
        assert result == "multi_tab"

        result = estimate_task_complexity("https://example.com", "切换tab")
        assert result == "multi_tab"

    def test_no_keywords_returns_medium(self):
        """没有关键词应该返回 'medium'"""
        from device_selector import estimate_task_complexity

        result = estimate_task_complexity("https://example.com", "做点什么")
        assert result == "medium"

    def test_case_insensitive(self):
        """关键词匹配应该不区分大小写"""
        from device_selector import estimate_task_complexity

        result = estimate_task_complexity("https://example.com", "LOGIN登录")
        assert result == "complex"
