"""
tests/test_env_diag.py — Playwright-Omni env_diag.py TDD
Generated by p3-mattpocock-harness Solo Mode
"""

import pytest
import sys
import os
from pathlib import Path

SCRIPTS_DIR = Path(__file__).parent.parent / "scripts"


class TestEnvDiagScript:
    """TDD tests for env_diag.py"""

    def test_checks_required_packages(self):
        """env_diag.py 应该检查这些关键包"""
        source = (SCRIPTS_DIR / "env_diag.py").read_text(encoding='utf-8')

        required_packages = ["openai", "torch", "transformers", "playwright", "PIL", "numpy", "ultralytics"]
        for pkg in required_packages:
            assert pkg in source, f"Missing package check: {pkg}"

    def test_checks_blip2_model_path(self):
        """env_diag.py 应该检查 BLIP2 模型路径"""
        source = (SCRIPTS_DIR / "env_diag.py").read_text(encoding='utf-8')

        assert "BLIP2" in source or "blip" in source.lower()
        assert "icon_caption" in source

    def test_checks_yolo_model_path(self):
        """env_diag.py 应该检查 YOLO 模型路径"""
        source = (SCRIPTS_DIR / "env_diag.py").read_text(encoding='utf-8')

        assert "icon_detect" in source
        assert "model.pt" in source

    def test_has_chromium_check(self):
        """env_diag.py 应该检查 Chromium"""
        source = (SCRIPTS_DIR / "env_diag.py").read_text(encoding='utf-8')

        assert "chromium" in source.lower()

    def test_chromium_path_uses_correct_variable(self):
        """Bug 验证：chromium_path 变量名拼写正确"""
        source = (SCRIPTS_DIR / "env_diag.py").read_text(encoding='utf-8')

        # 查找 chromium_path 的定义和使用
        lines = source.split('\n')
        for i, line in enumerate(lines):
            if 'chromium_path' in line and ':=' in line:
                # 找到 walrus operator 使用行
                # 提取变量名
                import re
                match = re.search(r'(\w+)\s*:=\s*chromium_path', line)
                if match:
                    var_name = match.group(1)
                    # 变量名应该是 chromium_path 或类似，不应该有额外的 'i'
                    assert var_name == 'chromium_path' or 'chromiumium' not in var_name, \
                        f"Typo in chromium variable name: {var_name}"
