"""
tests/test_preflight.py — Playwright-Omni preflight_check TDD
Generated by p3-mattpocock-harness Solo Mode
"""

import pytest
import sys
from pathlib import Path

# Add scripts to path for imports
SCRIPTS_DIR = Path(__file__).parent.parent / "scripts"
sys.path.insert(0, str(SCRIPTS_DIR))

# Import the function under test
from preflight_check import _check_import


class TestCheckImport:
    """TDD tests for _check_import function"""

    def test_check_import_success_returns_true(self):
        """成功导入应返回 (True, '')"""
        ok, msg = _check_import("os", "import os")
        assert ok is True, f"Expected True, got {ok}"
        assert msg == "", f"Expected empty message, got '{msg}'"

    def test_check_import_failure_returns_false(self):
        """失败导入应返回 (False, 错误信息)"""
        ok, msg = _check_import("nonexistent_module_xyz", "import nonexistent_module_xyz")
        assert ok is False, f"Expected False, got {ok}"
        assert len(msg) > 0, "Expected error message on failure"
        # Python 3.13 可能返回中文"未安装"或英文"ModuleNotFoundError"
        assert any(kw in msg for kw in ["ModuleNotFoundError", "ImportError", "未安装", "No module named"]), \
            f"Expected error keyword in message, got: {msg}"

    def test_check_import_with_existing_module(self):
        """测试已安装的模块（如 json）"""
        ok, msg = _check_import("json", "import json")
        assert ok is True
        assert msg == ""

    def test_check_import_with_syntax_error(self):
        """语法错误的导入应返回失败"""
        ok, msg = _check_import("test", "from nonexistent_package import ")
        assert ok is False
        assert len(msg) > 0
