"""
tests/test_vision_decision.py — Playwright-Omni vision_decision TDD
Generated by p3-mattpocock-harness Solo Mode
"""

import pytest
import sys
from pathlib import Path
from unittest.mock import MagicMock, patch

# Add scripts to path for imports
SCRIPTS_DIR = Path(__file__).parent.parent / "scripts"
sys.path.insert(0, str(SCRIPTS_DIR))


class TestActionType:
    """TDD tests for ActionType enum"""

    def test_action_type_values(self):
        """ActionType 应该有所有预期的枚举值"""
        from vision_decision import ActionType

        expected = ["CLICK", "TYPE", "SCROLL", "WAIT", "GOTO", "SWITCH_TAB", "DONE", "FAIL"]
        actual = [e.value for e in ActionType]

        for e in expected:
            assert e in actual, f"Missing ActionType.{e}"

    def test_action_type_from_string(self):
        """ActionType 应该能从字符串创建"""
        from vision_decision import ActionType

        assert ActionType["CLICK"] == ActionType.CLICK
        assert ActionType["TYPE"] == ActionType.TYPE


class TestLLMDecision:
    """TDD tests for LLMDecision dataclass"""

    def test_llm_decision_creation(self):
        """LLMDecision 应该能正确创建"""
        from vision_decision import LLMDecision, ActionType

        decision = LLMDecision(
            action=ActionType.CLICK,
            target="登录按钮",
            value="",
            thought="点击登录按钮继续",
            confidence=0.95,
            raw_response="原始响应内容"
        )

        assert decision.action == ActionType.CLICK
        assert decision.target == "登录按钮"
        assert decision.confidence == 0.95

    def test_llm_decision_defaults(self):
        """LLMDecision 默认值测试"""
        from vision_decision import LLMDecision, ActionType

        decision = LLMDecision(action=ActionType.CLICK)

        assert decision.target == ""
        assert decision.value == ""
        assert decision.thought == ""
        assert decision.confidence == 0.0
        assert decision.raw_response == ""

    def test_llm_decision_is_dataclass(self):
        """LLMDecision 应该是 dataclass"""
        from vision_decision import LLMDecision
        from dataclasses import is_dataclass

        assert is_dataclass(LLMDecision)

    def test_llm_decision_asdict(self):
        """LLMDecision 转换为字典测试"""
        from vision_decision import LLMDecision, ActionType
        from dataclasses import asdict

        decision = LLMDecision(
            action=ActionType.TYPE,
            target="用户名输入框",
            value="myuser",
            thought="输入用户名",
            confidence=0.9,
            raw_response="..."
        )

        d = asdict(decision)

        assert d["action"] == ActionType.TYPE
        assert d["target"] == "用户名输入框"
        assert d["value"] == "myuser"
        assert d["confidence"] == 0.9


class TestConversationMessage:
    """TDD tests for ConversationMessage dataclass"""

    def test_conversation_message_creation(self):
        """ConversationMessage 应该能正确创建"""
        from vision_decision import ConversationMessage

        msg = ConversationMessage(role="user", content="登录 GitHub")

        assert msg.role == "user"
        assert msg.content == "登录 GitHub"

    def test_conversation_message_roles(self):
        """ConversationMessage role 应该是常见值之一"""
        from vision_decision import ConversationMessage

        for role in ["user", "assistant", "system"]:
            msg = ConversationMessage(role=role, content="test")
            assert msg.role == role


class TestLLMClientInterfaces:
    """Test LLM client interface consistency"""

    def test_openai_client_api_key_stored(self):
        """OpenAIClient 应该存储 api_key 和 model"""
        from vision_decision import OpenAIClient
        from unittest.mock import patch, MagicMock

        # Mock openai module before importing OpenAI
        mock_openai = MagicMock()
        with patch.dict('sys.modules', {'openai': mock_openai}):
            # 直接创建实例，不调用 __init__
            client = object.__new__(OpenAIClient)
            client.api_key = "sk_test_12345"
            client.model = "gpt-4o"
            client.client = MagicMock()

            assert client.api_key == "sk_test_12345"
            assert client.model == "gpt-4o"

    def test_openai_client_custom_model(self):
        """OpenAIClient 应该支持自定义模型"""
        from vision_decision import OpenAIClient
        from unittest.mock import MagicMock

        client = object.__new__(OpenAIClient)
        client.api_key = "sk_test"
        client.model = "gpt-4o-mini"
        client.client = MagicMock()

        assert client.model == "gpt-4o-mini"

    def test_anthropic_client_api_key_stored(self):
        """AnthropicClient 应该存储 api_key 和 model"""
        from vision_decision import AnthropicClient

        client = object.__new__(AnthropicClient)
        client.api_key = "sk-ant_test"
        client.model = "claude-3-5-sonnet-20241022"
        client.client = MagicMock()

        assert client.api_key == "sk-ant_test"
        assert client.model == "claude-3-5-sonnet-20241022"

    def test_ollama_client_initialization(self):
        """OllamaClient 应该能用默认参数初始化"""
        from vision_decision import OllamaClient
        from unittest.mock import patch, MagicMock

        mock_openai = MagicMock()
        with patch.dict('sys.modules', {'openai': mock_openai}):
            import openai
            mock_openai_instance = MagicMock()
            openai.OpenAI.return_value = mock_openai_instance

            client = OllamaClient()

            assert client.base_url == "http://localhost:11434"
            assert client.model == "qwen2.5:3b"

    def test_ollama_client_custom_params(self):
        """OllamaClient 应该支持自定义 base_url 和 model"""
        from vision_decision import OllamaClient
        from unittest.mock import patch, MagicMock

        mock_openai = MagicMock()
        with patch.dict('sys.modules', {'openai': mock_openai}):
            import openai
            mock_openai_instance = MagicMock()
            openai.OpenAI.return_value = mock_openai_instance

            client = OllamaClient(base_url="http://custom:11434", model="llama3")

            assert client.base_url == "http://custom:11434"
            assert client.model == "llama3"


class TestVisionDecisionDefaults:
    """Test VisionDecision default configuration"""

    def test_vision_decision_default_provider(self):
        """VisionDecision 默认 provider 应该是 openai"""
        from vision_decision import VisionDecision
        import inspect

        sig = inspect.signature(VisionDecision.__init__)
        provider_param = sig.parameters.get('provider')

        assert provider_param is not None
        assert provider_param.default == "openai"

    def test_vision_decision_system_prompt(self):
        """VisionDecision 应该包含 system prompt"""
        from vision_decision import DEFAULT_SYSTEM_PROMPT

        # 检查 system prompt 是否包含关键信息
        assert len(DEFAULT_SYSTEM_PROMPT) > 100
        # 包含中文或英文关键词之一即可
        has_chinese = "浏览器" in DEFAULT_SYSTEM_PROMPT or "自动化" in DEFAULT_SYSTEM_PROMPT
        has_english = "browser" in DEFAULT_SYSTEM_PROMPT.lower() or "automation" in DEFAULT_SYSTEM_PROMPT.lower()
        assert has_chinese or has_english

    def test_vision_decision_supported_providers(self):
        """VisionDecision 应该支持所有预期的 provider"""
        from vision_decision import VisionDecision

        expected = ["openai", "anthropic", "zhipu", "doubao", "ollama"]
        actual = list(VisionDecision.PROVIDER_CLIENTS.keys())

        for e in expected:
            assert e in actual, f"Missing provider: {e}"
