"""
tests/test_cli.py — Playwright-Omni cli.py TDD
Generated by p3-mattpocock-harness Solo Mode
"""

import pytest
import sys
import os
from pathlib import Path
from unittest.mock import patch, MagicMock

# Add scripts to path for imports
SCRIPTS_DIR = Path(__file__).parent.parent / "scripts"
sys.path.insert(0, str(SCRIPTS_DIR))


class TestCliProviders:
    """TDD tests for cli.py provider configuration"""

    def test_provider_default_model_defined(self):
        """PROVIDER_DEFAULT_MODEL 应该定义所有支持的 provider"""
        # Import using exec to avoid modifying sys.path permanently
        import importlib.util
        spec = importlib.util.spec_from_file_location("cli", SCRIPTS_DIR / "cli.py")
        cli = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(cli)

        expected_providers = ["openai", "anthropic", "zhipu", "doubao", "ollama"]
        for p in expected_providers:
            assert p in cli.PROVIDER_DEFAULT_MODEL, f"Missing provider: {p}"

    def test_provider_api_key_defined(self):
        """PROVIDER_API_KEY 应该定义所有支持的 provider"""
        import importlib.util
        spec = importlib.util.spec_from_file_location("cli", SCRIPTS_DIR / "cli.py")
        cli = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(cli)

        expected_providers = ["openai", "anthropic", "zhipu", "doubao", "ollama"]
        for p in expected_providers:
            assert p in cli.PROVIDER_API_KEY, f"Missing API key config for: {p}"

    def test_ollama_api_key_is_placeholder(self):
        """Ollama 的 API key 应该是占位符 'ollama'（不需要真实 key）"""
        import importlib.util
        spec = importlib.util.spec_from_file_location("cli", SCRIPTS_DIR / "cli.py")
        cli = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(cli)

        assert cli.PROVIDER_API_KEY["ollama"] == "ollama"


class TestCliHelpText:
    """TDD tests for cli.py help text"""

    def test_cli_has_help_examples(self):
        """CLI 应该有示例用法在 docstring"""
        import importlib.util
        spec = importlib.util.spec_from_file_location("cli", SCRIPTS_DIR / "cli.py")
        cli = importlib.util.module_from_spec(spec)

        # Read source file for docstring
        source = (SCRIPTS_DIR / "cli.py").read_text(encoding='utf-8')

        assert "python cli.py --url" in source
        assert "--goal" in source  # --goal 参数存在即可
        assert "--max-steps" in source
        assert "--headless" in source
        assert "--check" in source
        assert "--list-providers" in source

    def test_list_providers_mentions_all_providers(self):
        """list_providers() 应该提到所有支持的 provider"""
        source = (SCRIPTS_DIR / "cli.py").read_text(encoding='utf-8')

        assert "openai" in source
        assert "anthropic" in source
        assert "zhipu" in source
        assert "doubao" in source
        assert "ollama" in source
